In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.5'

## Create and Read

#### 1DArray

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(5,)

In [8]:
arr1.dtype

dtype('int64')

In [9]:
arr1.ndim

1

In [10]:
arr1.size

5

#### 2D Array

In [12]:
arr2 = np.array([[1, 4, 5], [6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [13]:
arr2.ndim

2

In [15]:
arr2.shape #(row, col)

(2, 3)

In [16]:
arr2.dtype

dtype('int64')

In [17]:
arr2.size

6

#### 3D Array

In [23]:
arr3 = np.array([[[1, 4, 5], [6,7,4]], [[3, 5, 4], [5,8,7]], [[1, 4, 5], [6,7,4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [20]:
arr3.ndim

3

In [25]:
arr3.shape # Layers, Rowa, Columns

(3, 2, 3)

In [26]:
arr3.size

18

### Create Random Array

In [27]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.64741258, 0.23968478, 0.90681769],
        [0.81718514, 0.76534177, 0.04317421]],

       [[0.4207778 , 0.20189725, 0.03417987],
        [0.0955446 , 0.5519947 , 0.87669438]],

       [[0.12114316, 0.94824947, 0.49478179],
        [0.71123987, 0.25958882, 0.11493468]]])

In [28]:
randomArr.dtype

dtype('float64')

In [29]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
zeroes.ndim

3

In [32]:
full = np.full((3,2,3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [33]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [35]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [36]:
arr3[0][0][2]

np.int64(5)

In [39]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [40]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [41]:
arr3[1][0][1]

np.int64(5)

In [42]:
arr3[1, 0, 1]

np.int64(5)

#### Updtate and Delete

In [43]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [44]:
a1

array([[[0.75058376, 0.83989196],
        [0.02164144, 0.53636073],
        [0.20237972, 0.61917254]],

       [[0.28509221, 0.61903107],
        [0.86634683, 0.41819903],
        [0.32715521, 0.0079603 ]]])

In [45]:
a2

array([[[0.78329174, 0.98187861],
        [0.97665097, 0.72662126],
        [0.25789617, 0.97134442]],

       [[0.09175147, 0.80755068],
        [0.67298021, 0.92173842],
        [0.50489067, 0.20013529]]])

### Basic Math Operation

In [46]:
np.add(a1, a2)

array([[[1.5338755 , 1.82177057],
        [0.99829241, 1.26298198],
        [0.46027589, 1.59051696]],

       [[0.37684368, 1.42658175],
        [1.53932703, 1.33993745],
        [0.83204587, 0.20809559]]])

In [47]:
np.subtract(a1,a2)

array([[[-0.03270798, -0.14198665],
        [-0.95500954, -0.19026053],
        [-0.05551645, -0.35217188]],

       [[ 0.19334074, -0.18851961],
        [ 0.19336662, -0.50353938],
        [-0.17773546, -0.19217499]]])

In [48]:
np.divide(a1, a2)

array([[[0.95824292, 0.85539287],
        [0.02215882, 0.73815722],
        [0.78473334, 0.63743871]],

       [[3.10722234, 0.76655384],
        [1.28732883, 0.45370685],
        [0.64797238, 0.0397746 ]]])

In [49]:
np.multiply(a1, a2)

array([[[0.58792606, 0.82467195],
        [0.02113613, 0.38973111],
        [0.05219295, 0.60142979]],

       [[0.02615763, 0.49989896],
        [0.58303427, 0.38547012],
        [0.16517761, 0.00159314]]])

#### Statistical operations

In [51]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [52]:
sqrt

np.float64(5.0)

In [53]:
abs

np.int64(2)

In [54]:
power

np.int64(256)

In [55]:
log

np.float64(3.2188758248682006)

In [56]:
mins

np.float64(0.007960300312007007)

In [57]:
maxs

np.float64(0.9818786103701522)

### Update

In [58]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [59]:
arr3[0, 0, 2] = 900
arr3

array([[[  1,   4, 900],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [60]:
arr3.sort()
arr3

array([[[  1,   4, 900],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [61]:
# Reshape
arr3.shape

(3, 2, 3)

In [62]:
arr3_reshape = arr3.reshape((2, 3, 3))
arr3_reshape

array([[[  1,   4, 900],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [63]:
arr3_reshape.shape

(2, 3, 3)

### Append and Inserting

In [64]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [65]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [67]:
appd = np.append(zeroes, new_array, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [68]:
# Insert 
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [69]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [70]:
inserted_array = np.insert(zeroes, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [71]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.10237086, 0.4212027 , 0.30255885],
        [0.70601654, 0.83002163, 0.72166411]],

       [[0.7715251 , 0.04948804, 0.40379566],
        [0.57786766, 0.81331308, 0.93928385]],

       [[0.29004631, 0.0167854 , 0.99690773],
        [0.86445522, 0.54329381, 0.45378469]]])

In [74]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [75]:
arr5

array([[[0.70601654, 0.83002163, 0.72166411]],

       [[0.57786766, 0.81331308, 0.93928385]],

       [[0.86445522, 0.54329381, 0.45378469]]])

In [76]:
np.save("new_array", arr5)

In [77]:
np.load("new_array.npy")

array([[[0.70601654, 0.83002163, 0.72166411]],

       [[0.57786766, 0.81331308, 0.93928385]],

       [[0.86445522, 0.54329381, 0.45378469]]])